import asyncio
from typing import Any, Callable
import serial

class SerialTransport(asyncio.Transport):
    def __init__(
        self,
        loop: asyncio.AbstractEventLoop,
        protocol: asyncio.Protocol,
        serial_instance: serial.Serial,
    ) -> None: ...
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    @property
    def serial(self) -> serial.Serial: ...
    def get_extra_info(self, name: str, default: Any | None = ...) -> Any: ...
    def is_closing(self) -> bool: ...
    def close(self) -> None: ...
    def write(self, data: bytes) -> None: ...
    def can_write_eof(self) -> bool: ...
    def resume_reading(self) -> None: ...
    def set_write_buffer_limits(
        self, high: int | None = ..., low: int | None = ...
    ) -> None: ...
    def get_write_buffer_size(self) -> int: ...
    def write_eof(self) -> None: ...
    def abort(self) -> None: ...
    def flush(self) -> None: ...

async def create_serial_connection(
    loop: asyncio.AbstractEventLoop,
    protocol_factory: Callable[[], asyncio.Protocol],
    url: str,
    *args: Any,
    **kwargs: Any,
) -> tuple[SerialTransport, asyncio.Protocol]: ...
