from typing import Any
from typing_extensions import Buffer
import enum
import io

class RS485Settings(object): ...

class SerialBase(io.RawIOBase):
    class ParitiesType(enum.Enum):
        PARITY_NONE = ...
        PARITY_EVEN = ...
        PARITY_ODD = ...
        PARITY_MARK = ...
        PARITY_SPACE = ...

    class ByteSizeType(enum.Enum):
        FIVEBITS = ...
        SIXBITS = ...
        SEVENBITS = ...
        EIGHTBITS = ...

    class StopBitsType(enum.Enum):
        STOPBITS_ONE = ...
        STOPBITS_ONE_POINT_FIVE = ...
        STOPBITS_TWO = ...

    # default values, may be overridden in subclasses that do not support all values
    BAUDRATES: tuple[int] = ...
    BYTESIZES: tuple[int] = ...
    PARITIES: tuple[ParitiesType] = ...
    STOPBITS: tuple[float] = ...

    def __init__(
        self,
        port: str | None = ...,
        baudrate: int = ...,
        bytesize: ByteSizeType = ...,
        parity: ParitiesType = ...,
        stopbits: StopBitsType = ...,
        timeout: float | None = ...,
        xonxoff: bool = ...,
        rtscts: bool = ...,
        write_timeout: float | None = ...,
        dsrdtr: bool | None = ...,
        inter_byte_timeout: float | None = ...,
        exclusive: bool | None = ...,
        **kwargs: dict[str, float | None],
    ) -> None: ...
    @property
    def port(self) -> str | None: ...
    @port.setter
    def port(self, port: str | None) -> None: ...
    @property
    def baudrate(self) -> int: ...
    @baudrate.setter
    def baudrate(self, baudrate: int) -> None: ...
    @property
    def bytesize(self) -> ByteSizeType: ...
    @bytesize.setter
    def bytesize(self, bytesize: ByteSizeType) -> None: ...
    @property
    def exclusive(self) -> bool | None: ...
    @exclusive.setter
    def exclusive(self, exclusive: bool | None) -> None: ...
    @property
    def parity(self) -> ParitiesType: ...
    @parity.setter
    def parity(self, parity: ParitiesType) -> None: ...
    @property
    def stopbits(self) -> StopBitsType: ...
    @stopbits.setter
    def stopbits(self, stopbits: StopBitsType) -> None: ...
    @property
    def timeout(self) -> float | None: ...
    @timeout.setter
    def timeout(self, timeout: float | None) -> None: ...
    @property
    def write_timeout(self) -> float | None: ...
    @write_timeout.setter
    def write_timeout(self, timeout: float | None) -> None: ...
    @property
    def inter_byte_timeout(self) -> float | None: ...
    @inter_byte_timeout.setter
    def inter_byte_timeout(self, ic_timeout: float | None) -> None: ...
    @property
    def xonxoff(self) -> bool: ...
    @xonxoff.setter
    def xonxoff(self, xonxoff: bool) -> None: ...
    @property
    def rtscts(self) -> bool: ...
    @rtscts.setter
    def rtscts(self, rtscts: bool) -> None: ...
    @property
    def dsrdtr(self) -> bool: ...
    @dsrdtr.setter
    def dsrdtr(self, dsrdtr: bool | None = ...) -> None: ...
    @property
    def rts(self) -> bool: ...
    @rts.setter
    def rts(self, value: bool) -> None: ...
    @property
    def dtr(self) -> bool: ...
    @dtr.setter
    def dtr(self, value: bool) -> None: ...
    @property
    def break_condition(self) -> bool: ...
    @break_condition.setter
    def break_condition(self, value: bool) -> None: ...
    @property
    def rs485_mode(self) -> RS485Settings | None: ...
    @rs485_mode.setter
    def rs485_mode(self, rs485_settings: RS485Settings | None) -> None: ...
    def get_settings(self) -> dict[str, Any]: ...
    def apply_settings(self, d: dict[str, Any]) -> None: ...
    def __repr__(self) -> str: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def readinto(self, b: Buffer) -> int: ...
    def send_break(self, duration: float = ...) -> None: ...
    def flushInput(self) -> None: ...
    def flushOutput(self) -> None: ...
    def inWaiting(self) -> int: ...
    def sendBreak(self, duration: float = ...) -> None: ...
    def setRTS(self, value: bool = ...) -> None: ...
    def setDTR(self, value: bool = ...) -> None: ...
    def getCTS(self) -> bool: ...
    def getDSR(self) -> bool: ...
    def getRI(self) -> bool: ...
    def getCD(self) -> bool: ...
    def setPort(self, port: str | None) -> None: ...
    @property
    def writeTimeout(self) -> float | None: ...
    @writeTimeout.setter
    def writeTimeout(self, timeout: float | None) -> None: ...
    @property
    def interCharTimeout(self) -> float | None: ...
    @interCharTimeout.setter
    def interCharTimeout(self, interCharTimeout: float | None) -> None: ...
    def getSettingsDict(self) -> dict[str, Any]: ...
    def applySettingsDict(self, d: dict[str, Any]) -> None: ...
    def isOpen(self) -> bool: ...
    def read_all(self) -> bytes | None: ...
    def read_until(self, expected: str = ..., size: int | None = ...) -> bytes: ...
    def iread_until(self, *args: str, **kwargs: int) -> bytes: ...

class PlatformSpecificBase(object): ...
class PlatformSpecific(PlatformSpecificBase): ...

class Serial(SerialBase, PlatformSpecific):
    def open(self) -> None: ...
    def close(self) -> None: ...
    @property
    def in_waiting(self) -> int: ...
    def read(self, size: int = ...) -> bytes: ...
    def cancel_read(self) -> None: ...
    def cancel_write(self) -> None: ...
    def write(self, data: Buffer) -> int: ...
    def flush(self) -> None: ...
    def reset_input_buffer(self) -> None: ...
    def reset_output_buffer(self) -> None: ...
    def send_break(self, duration: float = ...) -> None: ...
    @property
    def cts(self) -> bool: ...
    @property
    def dsr(self) -> bool: ...
    @property
    def ri(self) -> bool: ...
    @property
    def cd(self) -> bool: ...

PARITY_NONE = SerialBase.ParitiesType.PARITY_NONE
PARITY_EVEN = SerialBase.ParitiesType.PARITY_EVEN
PARITY_ODD = SerialBase.ParitiesType.PARITY_ODD
PARITY_MARK = SerialBase.ParitiesType.PARITY_MARK
PARITY_SPACE = SerialBase.ParitiesType.PARITY_SPACE

FIVEBITS = SerialBase.ByteSizeType.FIVEBITS
SIXBITS = SerialBase.ByteSizeType.SIXBITS
SEVENBITS = SerialBase.ByteSizeType.SEVENBITS
EIGHTBITS = SerialBase.ByteSizeType.EIGHTBITS

STOPBITS_ONE = SerialBase.StopBitsType.STOPBITS_ONE
STOPBITS_ONE_POINT_FIVE = SerialBase.StopBitsType.STOPBITS_ONE_POINT_FIVE
STOPBITS_TWO = SerialBase.StopBitsType.STOPBITS_TWO
